@baseUrl = http://localhost:3000


######### Rutas de autenticación #########
### Registro de un usuario nuevo
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Usuario Prueba Yo",
  "email": "2jmalvarez@gmail.com",
  "password": "2jmalvarez@gmail.com"
}

### Inicio de sesión
# @name Auth
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "2jmalvarez@gmail.com",
  "password": "2jmalvarez@gmail.com"
}

### Almacenar el token de autenticación
@token = {{Auth.response.body.data.token}}


######### Rutas de pacientes #########

### Generar un nombre aleatorio en español utilizando un servicio externo
# @name RandomName
GET https://randomuser.me/api/?nat=es

### Crear un nuevo usuario con el nombre aleatorio generado
@randomName = {{RandomName.response.body.results[0].name.first}} {{RandomName.response.body.results[0].name.last}}
@randomGender = {{RandomName.response.body.results[0].gender}}
@randomAddress = {{RandomName.response.body.results[0].location.street.name}} {{RandomName.response.body.results[0].location.street.number}}
@randomBirthDate = {{RandomName.response.body.results[0].dob.date}}

### Crear un nuevo paciente
POST {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{randomName}}",
  "birth_date":"{{randomBirthDate}}",
  "gender": "{{randomGender}}",
  "address": "{{randomAddress}}"
}

### Obtener todos los pacientes
GET {{baseUrl}}/patients
Authorization: Bearer {{token}}


### Obtener un paciente por ID
GET {{baseUrl}}/patients/100
Authorization: Bearer {{token}}


### Obtener todas las observaciones de un paciente
GET {{baseUrl}}/patients/:id/observations
Authorization: Bearer {{token}}


### Crear una nueva observación clínica para un paciente
POST {{baseUrl}}/patients/:id/observations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "Blood Pressure",
  "value": "120/80",
  "unit": "mmHg",
  "date": "2024-11-29T10:00:00Z"
}


# Rutas de observaciones

### Actualizar una observación existente
PUT {{baseUrl}}/observations/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "value": "130/85",
  "unit": "mmHg"
}


### Eliminar una observación
DELETE {{baseUrl}}/observations/:id
Authorization: Bearer {{token}}


### Observaciones Fhir

### Crear observacion Fhir
POST {{baseUrl}}/observations/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "observation_code":"213", 
  "value":"12", 
  "date":"2024-11-29T10:00:00Z"
}
 